# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tjob.proto\x12\x03job\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x10\n\x08job_type\x18\x02 \x01(\t\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07payload\x18\x0f \x01(\x0c\"m\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x10\n\x08job_type\x18\x02 \x01(\t\x12+\n\x08\x64uration\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x0f\n\x07payload\x18\x0f \x01(\x0c\x32=\n\nJobManager\x12/\n\nJobService\x12\x0f.job.JobRequest\x1a\x10.job.JobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBREQUEST']._serialized_start=83
  _globals['_JOBREQUEST']._serialized_end=188
  _globals['_JOBRESPONSE']._serialized_start=190
  _globals['_JOBRESPONSE']._serialized_end=299
  _globals['_JOBMANAGER']._serialized_start=301
  _globals['_JOBMANAGER']._serialized_end=362
# @@protoc_insertion_point(module_scope)
