import asyncio

from __init__ import logger
from grpclib.health.service import Health
from grpclib.server import Server, Stream
# generated by protoc
from helloworld_grpc import GreeterBase
from helloworld_pb2 import HelloReply, HelloRequest

default_prompt = """
"""

class Greeter(GreeterBase):

    async def SayHello(self, stream: Stream[HelloRequest, HelloReply]) -> None:
        request = await stream.recv_message()
        assert request is not None
        message = f'Hello, {request.name}!'
        await stream.send_message(HelloReply(message=message))

class AIServer:
    def __init__(self, input_queue, output_queue) -> None:
        self.input_queue = input_queue
        self.output_queue = output_queue
        self.server = Server([Greeter(), Health()])
        
    def start(self, host: str, port: int):
        self.host: str = host
        self.port: int = port
        return self.server.start(self.host, self.port)
    
    def wait_closed(self):
        return self.server.wait_closed()


async def run(input_queue: asyncio.Queue, output_queue: asyncio.Queue, host='127.0.0.1', port=50051):
    try:
        server = AIServer(input_queue, output_queue)
        await server.start(host, port)
        logger.info(f'Serving on {host}:{port}')
        await server.wait_closed()
    except asyncio.CancelledError: 
        logger.info("Server gracefully shut down")
