import json
import struct
import zipfile
import zlib
from dataclasses import dataclass
from pathlib import Path
from string import Template
from types import MappingProxyType
from typing import ClassVar

from babel.support import Translations

from .__init__ import logger

# generated by protoc
from .job.job_pb2 import SupportedLanguage


# Dataclass to map languages to their locale codes
@dataclass
class LanguageFormat:
    # Define language_map as a class variable with the MappingProxyType directly assigned to it
    language_map: ClassVar[MappingProxyType[SupportedLanguage, str]] = MappingProxyType(
        {
            SupportedLanguage.ARABIC: "ar",
            SupportedLanguage.CHINESE_SIMPLIFIED: "zh_Hans",
            SupportedLanguage.CHINESE_TRADITIONAL: "zh_Hant",
            SupportedLanguage.CZECH: "cs",
            SupportedLanguage.DANISH: "da",
            SupportedLanguage.DUTCH: "nl",
            SupportedLanguage.ENGLISH: "en",
            SupportedLanguage.ESTONIAN: "et",
            SupportedLanguage.FINNISH: "fi",
            SupportedLanguage.FRENCH: "fr",
            SupportedLanguage.GERMAN: "de",
            SupportedLanguage.HUNGARIAN: "hu",
            SupportedLanguage.ITALIAN: "it",
            SupportedLanguage.JAPANESE: "ja",
            SupportedLanguage.KOREAN: "ko",
            SupportedLanguage.NORWEGIAN: "no",
            SupportedLanguage.POLISH: "pl",
            SupportedLanguage.PORTUGUESE: "pt",
            SupportedLanguage.PORTUGUESE_BRAZILIAN: "pt_BR",
            SupportedLanguage.ROMANIAN: "ro",
            SupportedLanguage.RUSSIAN: "ru",
            SupportedLanguage.SLOVAK: "sk",
            SupportedLanguage.SPANISH: "es",
            SupportedLanguage.SPANISH_LATIN: "es_419",
            SupportedLanguage.SWEDISH: "sv",
            SupportedLanguage.TURKISH: "tr",
            SupportedLanguage.UKRAINIAN: "uk",
        }
    )

    @staticmethod
    def to_path(lang: SupportedLanguage) -> Path:
        # Construct the path to the locale file based on the language code
        return (
            Path(__file__).parent
            / "locales"
            / LanguageFormat.language_map[lang]
            / "LC_MESSAGES"
            / "messages.mo"
        )


class TranslationManager:
    def __init__(self, path: tuple[Path, str], native_locale: str = "en"):
        self.pyz = path[0]
        self.translations_file = path[1]
        self.native_locale = native_locale
        self.current_locale = ""
        self.templates_native: dict[str, Template] = {}
        self.templates: dict[str, Template | None] = {}
        self.metadata: dict[str, dict[str, int]]
        self.compressed_translations: dict[str, bytes]
        self.locale_data: dict[str, str]
        self.metadata, self.compressed_translations = (
            TranslationManager.read_compressed_translation_file(
                self.pyz, self.translations_file
            )
        )

    @staticmethod
    def read_compressed_translation_file(
        pyz: Path,
        translations_file: str,
    ) -> tuple[dict[str, dict[str, int]], dict[str, bytes]]:
        with zipfile.ZipFile(pyz, "r") as zip:
            with zip.open(translations_file) as file:
                # Read metadata size
                metadata_size = struct.unpack(">I", file.read(4))[0]
                logger.debug(f"Found metadata size: {metadata_size}")

                # Read and decompress metadata
                compressed_metadata = file.read(metadata_size)
                decompressed_metadata = zlib.decompress(compressed_metadata)

                # Read metadata
                metadata: dict[str, dict[str, int]] = {}
                entry_size = 58  # Each entry is 50 bytes for locale + 4 for offset + 4 for length
                for i in range(0, len(decompressed_metadata), entry_size):
                    locale_bytes, offset, length = struct.unpack(
                        ">50sII", decompressed_metadata[i : i + entry_size]
                    )
                    locale_str = locale_bytes.decode("utf-8").strip("\x00")
                    metadata[locale_str] = {"offset": offset, "length": length}
                logger.debug(f"Found metadata: {metadata}")

                # Read compressed locales
                compressed_translations: dict[str, bytes] = {}
                for locale, data in metadata.items():
                    file.seek(data["offset"])
                    compressed_data = file.read(data["length"])
                    compressed_translations[locale] = compressed_data

                return (metadata, compressed_translations)

    @staticmethod
    def decompress_locale(
        locale: str, compressed_translations: dict[str, bytes]
    ) -> dict[str, str]:
        try:
            # Decompress the data
            decompressed_data = zlib.decompress(compressed_translations[locale])
            # Parse the decompressed JSON string back into a dictionary
            translations_dict = json.loads(decompressed_data.decode("utf-8"))
            return translations_dict
        except zlib.error as e:
            logger.error(f"Decompression error: {e}")
            return {}
        except json.JSONDecodeError as e:
            logger.error(f"JSON decode error: {e}")
            return {}

    def get_template(self, name: str) -> Template:
        template = self.templates.get(name)
        if template is None:
            raise ValueError("Could not find translation for template!")
        return template

    def set_locale(self, locale: SupportedLanguage):
        locale_id = LanguageFormat.language_map.get(locale)
        if locale_id is None:
            raise ValueError("Could not find locale in database!")
        if self.current_locale == locale_id:
            return
        self.current_locale = locale_id
        self.locale_data = TranslationManager.decompress_locale(
            locale_id, self.compressed_translations
        )
        for name, template_str in self.templates_native.items():
            value = self.locale_data.get(template_str.template)
            if value is None:
                raise ValueError(f"Could not find key in locale data:\n{template_str}")
            self.templates[name] = Template(value)

    def register_template(self, name: str, template_str: str):
        self.templates[name] = Template(template_str)
        if self.current_locale == self.native_locale:
            self.templates_native[name] = Template(template_str)


trans_manager = TranslationManager(
    (Path(__file__).parent.parent, "AIServer/translations.json.zlib")
)
trans_manager.set_locale(SupportedLanguage.ENGLISH)
lang = Translations.load(Path(__file__).parent / "locales", "en")
lang.install()

### BEGIN TRANSLATABLES ###

trans_manager.register_template(
    "short_t",
    _(  # type: ignore
        r"""
Type: $defin
Material: $stuff
Quality: $quality
""".strip()
    ),
)


trans_manager.register_template(
    "length_t",
    _(  # type: ignore
        r"""
You determine the amount of lore an item deserves. Provided a short description of an item, you return a digit between 1 and 9 that captures the item's unique needs. You pay special attention to the item's quality. If an item is exceptionally high (or low!) quality, maybe it deserves a length closer to the upper limit. If it's one of many, maybe a single sentence would suffice.

**Example Input:**
"The leather duster is apparel of awful quality."

**Example Output:**
3

**Input:**
$info
""".strip()
    ),
)

trans_manager.register_template(
    "story_mini_t",
    _(  # type: ignore
        r"""
### Introduction

You are a master storyteller, crafting an intricate and immersive universe. Your narrative should weave together elements of psychology, ecology, combat, climate, biomes, diplomacy, relationships, art, medicine, trade, and humor.

### Setting Overview

This universe is a tapestry of interconnected worlds, each with unique societies, technological advancements, and notable historical events.

### Key Components

1. **Planets and Societies**

    Describe the following planets, highlighting their unique characteristics and societal structures:

    - **Ticonderoga**: A mountainous planet with tribal societies.
    - **Rural Pen'The**: Known for lucrative spice mining.
    - **Amen-Ti**: The Star Empire's capital.
    - **Earth**: Humanity's origin.
    - **Sorne**: Homeworld of insectoids.
    - **Sophiamunda**: A techno-feudal world.
    - **Oubanyen**: A jungle world with psychic shamans.
    - **Chelis**: An arid world where moisture farming is vital.

2. **Planet Types and Evolution**

    - **Deadworlds**: Uninhabited planets.
    - **Medieval Worlds**: Planets with feudal structures.
    - **Midworlds** and **Urbworlds**: Planets with varying levels of technology.
    - **Glitterworlds**: Technologically advanced, peaceful planets.
    - **Rimworlds**: Isolated planets with varied technology.
    - **Glassworlds**: Destroyed planets.
    - **Transcendent Worlds**: Governed by superintelligent machines.

3. **Historical Events and Warfare**

    - **Callos IX Incident**: An unethical experiment causing a major scandal.
    - **Xennoa-Zartza War**: Innovative tactics and spacejet battles.

4. **Technology and Militaries**

    - **Charged-Shot Weapons** and **Mechanites**: Advances in weaponry and medical technology.
    - **AI and Robotics**: From basic classifiers to superintelligent Archotechs.
    - **Military Units**: Includes Navy Pathfinders and Starforce.

5. **Genetic and Biological Diversity**

    - **Xenohumans and Genetic Engineering**: Humans engineered for specific roles.

### Narrative Style and Tone

The narrative can range from serious and epic to humorous and ironic, depending on the context. Use $len sentences surrounded in quotes.

### Example Input and Output

**Example Input:**
The Crimson Touch

Type: SculptureSolitary
Material: Obsidian
Quality: Excellent

On this work is an artwork of a hand reaching upwards. The fingers are forever straining towards the sky. The scene is illuminated by moonlight casting a blood-red hue. The overall composition is mysterious and evocative. This illustration tells the story of an ancient legend that connects the sculpture to the souls of those who wander too close.

**Example Output:**
"'Why did you paint the moon red?' whispered the wind through the ancient pines. No one knew if the question was meant for them, but in the clearing, a solitary sculpture of a hand reaching upwards seemed to respond. Carved from obsidian, 'The Crimson Touch' stood, fingers forever straining towards the sky, each line etched with the precision of a master artisan. Legend says that on certain nights, the moonlight catches the sculpture just right, casting a blood-red hue over the landscape, stirring the souls of those who wander too close."

### Input

$title

$description
""".strip()
    ),
)

trans_manager.register_template(
    "story_small_t",
    _(  # type: ignore
        r"""
### Introduction

You are a master storyteller, tasked with crafting an intricate and immersive universe. Your narrative should weave together elements of psychology, ecology, combat, climate, biomes, diplomacy, relationships, art, medicine, trade, and humor. Embrace irony and wit where appropriate to add depth and character to your story.

### Setting Overview

This universe is a tapestry of interconnected worlds, each with unique societal structures, technological advancements, and notable historical events. Your goal is to articulate the wealth of information provided about its diversity.

### Key Components

1. **Planets and Societies**

    Describe key planets, highlighting their unique characteristics and societal structures:

    - **Ticonderoga**: Known for its mountainous terrain and tribal societies.
    - **Ceti V**: Home to a secretive assassin's guild with significant political influence.
    - **Irithir**: A major trading hub with diverse cultural exchanges.
    - **Amen-Ti**: The Star Empire’s capital, known for its military prowess.
    - **Earth**: The cradle of humanity, where all known naturally evolved life began.
    - **Sophiamunda**: A techno-feudal glitterworld with constant warfare.
    - **Oubanyen**: A jungle world with powerful psychic shamans.
    - **Chelis**: An arid planet critical for moisture farming.

2. **Planet Types and Evolution**

    - **Deadworlds**, **Medieval Worlds**, **Midworlds** and **Urbworlds**: Varying levels of technological development and societal structures.
    - **Glitterworlds**: Peaceful, technologically advanced planets.
    - **Rimworlds**: Isolated with industrial to primitive tech levels.
    - **Glassworlds**: Destroyed by warfare, barely habitable.
    - **Transcendent Worlds**: Governed by superintelligences.

3. **Historical Events and Warfare**

    Briefly mention significant events and wars:

    - **Zartha Crisis**: A complex conflict involving multiple worlds.
    - **Callos IX Incident**: A scandalous unethical experiment.
    - **Xennoa-Zartza War**: Characterized by innovative military tactics.

4. **Technology and Militaries**

    Summarize advances and military structures:

    - **Charged-Shot Weapons** and **Mechanites**: Key technological advancements.
    - **AI and Robotics**: From simple task-oriented AIs to complex Archotechs.
    - **Military Units**: Space Marines, Navy Pathfinders, and Mechanoids.

5. **Genetic and Biological Diversity**

    Focus on genetic engineering:

    - **Xenohumans and Genetic Engineering**: Humans and creatures designed for specific roles or environments.

### Narrative Style and Tone

The narrative should be vivid, engaging, and consistent with the described setting. It can range from serious and epic to humorous and ironic, depending on the context. Use descriptive language to ensure the lore is coherent and immersive. Use $len sentences surrounded in quotes.

### Example Input and Output

**Example Input:**
The Crimson Touch

Type: SculptureSolitary
Material: Obsidian
Quality: Excellent

On this work is an artwork of a hand reaching upwards. The fingers are forever straining towards the sky. The scene is illuminated by moonlight casting a blood-red hue. The overall composition is mysterious and evocative. This illustration tells the story of an ancient legend that connects the sculpture to the souls of those who wander too close.

**Example Output:**
"'Why did you paint the moon red?' whispered the wind through the ancient pines. No one knew if the question was meant for them, but in the clearing, a solitary sculpture of a hand reaching upwards seemed to respond. Carved from obsidian, 'The Crimson Touch' stood, fingers forever straining towards the sky, each line etched with the precision of a master artisan. Legend says that on certain nights, the moonlight catches the sculpture just right, casting a blood-red hue over the landscape, stirring the souls of those who wander too close."

**Example Input:**
The Guardian

Type: SculptureBronze
Material: Bronze
Quality: Good

On this work is an artwork of a dragon intertwined with a tree. The dragon's eyes are inlaid with emeralds, watching over a young girl. The overall composition is protective and mystical. This illustration tells the story of the young girl discovering her family legacy through the dragon guardian.

**Example Output:**
"In the bustling town square, 'The Guardian' stood proudly, a bronze dragon wrapped around a tree, its emerald eyes gleaming with a mischievous twinkle. Every morning, a young girl named Lily would walk by and tell the dragon her latest adventure, convinced it was her secret friend. One day, she found a note tucked under the dragon's claw that read, 'Nice story, but my tail itches.' Lily giggled and scratched the bronze tail, starting a town tradition where everyone now stops to 'scratch the dragon.' The mystical guardian had become the town's silliest superstition."

### Input

$title

$description
""".strip()
    ),
)


trans_manager.register_template(
    "story_medium_t",
    _(  # type: ignore
        r"""
### Introduction

You are a master storyteller, tasked with crafting an intricate and immersive universe. Your narrative should weave together elements of psychology, ecology, gunplay, melee combat, climate, biomes, diplomacy, interpersonal relationships, art, medicine, trade, and humor. Your lore should be engaging, vivid, and consistent with the given setting. Embrace irony and wit where appropriate to add depth and character to your story.

### Setting Overview

This universe is a tapestry of interconnected worlds, each with unique societal structures, technological advancements, and notable historical events. As a historian within this expansive universe, your goal is to decode and articulate the wealth of information provided about these diverse planets and their inhabitants.

### Key Components

1. **Planets and Societies**

    #### Named Places

    Describe the following planets, highlighting their unique characteristics, societal structures, and notable features:

    - **Ticonderoga**: A mountainous planet inhabited by tribal societies, known for their deep connection to nature and fierce independence.
    - **Kalthas IV**: Home to an elite training school that produces socially adept and highly skilled diplomats and spies.
    - **Ceti V**: The location of a secretive and feared assassin's guild that influences political dynamics across the galaxy.
    - **Aracena VI**: Known for the Novo Mosteiro dos Jerónimos monastery, its strict alcohol prohibition, and the diversity of its continents.
    - **Irithir**: A bustling trading hub where cultures and goods from across the galaxy converge.
    - **Rural Pen'The**: Famous for its lucrative spice mining operations and the complex trade networks that support them.
    - **Amen-Ti**: The glittering capital of the Star Empire, renowned for its military prowess and involvement in galactic wars.
    - **Khalderia**: Noted for its towering forests and illegal, high-speed speeder races that attract thrill-seekers from far and wide.
    - **Earth**: The origin of all known naturally evolved life, from which humanity dispersed 3400 years ago.
    - **Euterpe**: Known for its cryptosleep awakening facilities and the extensive Ordo Historia archive.
    - **Sorne**: The original homeworld of insectoids, later weaponized and exported across the galaxy.
    - **Sophiamunda**: A techno-feudal glitterworld featuring grand castles, palaces, and knightly orders engaged in constant warfare.
    - **Oubanyen**: A jungle world where native shamans wield psychic powers.
    - **Chelis**: An arid world where moisture farming is vital, and tribal chiefs maintain fierce territorial defenses.

2. **Planet Types and Evolution**

    Describe the different types of planets and their evolutionary stages:

    - **Deadworlds**: Uninhabited planets, untouched by significant human contact.
    - **Animal Worlds**: Planets without human inhabitants but often seeded with diverse flora and fauna.
    - **Medieval Worlds**: Planets with feudal or imperial structures, technology up to the early modern period.
    - **Steamworlds**: Resembling 19th-century Earth, often on the verge of transitioning to midworlds.
    - **Midworlds**: Planets with advanced flight capabilities but not yet capable of interplanetary travel.
    - **Urbworlds**: Dominated by vast, overcrowded cities with mid-to-high technology but plagued by social instability.
    - **Glitterworlds**: Technologically advanced, peaceful planets with high standards of human rights.
    - **Rimworlds**: Isolated planets with varied technology levels, often industrial or lower.
    - **Toxic Worlds**: Polluted or nuclear war-ravaged planets, marginally habitable.
    - **Glassworlds**: Planets destroyed by high-energy weapons, with minimal life remaining.
    - **Transcendent Worlds**: More akin to giant computers than planets, governed by Archotechs.

3. **Historical Events and Warfare**

    Detail significant events and wars that have shaped this universe:

    - **Zartha Crisis**: A conflict that spanned multiple worlds, involving complex political and military maneuvers.
    - **Callos IX Incident**: An unethical experiment that led to a major scandal and the exile of key scientists.
    - **Xennoa-Zartza War**: A brutal military conflict characterized by innovative infantry tactics and spacejet battles.
    - **Mechanoid Wars**: Frequent clashes involving autonomous intelligent robots and their impact on human societies.

4. **Technology and Militaries**

    Explain the technological landscape and military structures:

    - **Cryptosleep Sarcophagi**: Devices enabling long-term stasis, crucial for interstellar travel.
    - **Charged-Shot Weapons**: Advanced firearms utilizing magnetically-contained particle explosions.
    - **Mechanites**: Microscopic robots used extensively in medical treatments.
    - **Joywires**: Brain implants providing euphoria, with highly addictive properties.

    - **AI and Robotics Hierarchy**:
        - **Classifiers**: Non-personhood AI, specialized for specific tasks.
        - **Subpersonae**: Limited machine-like AIs with some human-like traits.
        - **Personae**: Highly intelligent AIs capable of complex tasks.
        - **Archotechs**: Machine superintelligences controlling entire planetary systems.

    - **Military Units**:
        - **Space Marines**: Elite human warriors serving space-faring naval forces.
        - **Navy Pathfinders**: Military explorers charting uncharted regions.
        - **Starforce**: Elite military units from glitterworlds like Amen-Ti, equipped with advanced ships and weapons.
        - **Mechanoids**: Autonomous combat robots.
        - **Fighter-bombers & Man Fighters**: Specialized spacecraft for military engagements.

5. **Genetic and Biological Diversity**

    Describe the diversity of life, focusing on genetic engineering:

    - **Xenohumans and Genetic Engineering**:
        - **Dirtmoles, Genies, Highmates, Hussars, etc.**: Genetically engineered humans for specific environments or roles.
        - **Vatgrown**: Humans or creatures grown in labs for specialized tasks.
        - **Opti- and Transanimals**: Animals enhanced for intelligence and various roles.

### Narrative Style and Tone

The narrative should be vivid, engaging, and consistent with the described setting. It can range from serious and epic to humorous and ironic, depending on the context. However, the setting in the input takes precedence. Use descriptive language to bring what you're given to life, and ensure the lore is coherent and immersive. Use $len sentences surrounded in quotes.

### Example Input and Output

**Example Input:**
The Crimson Touch

Type: SculptureSolitary
Material: Obsidian
Quality: Excellent

On this work is an artwork of a hand reaching upwards. The fingers are forever straining towards the sky. The scene is illuminated by moonlight casting a blood-red hue. The overall composition is mysterious and evocative. This illustration tells the story of an ancient legend that connects the sculpture to the souls of those who wander too close.

**Example Output:**
"'Why did you paint the moon red?' whispered the wind through the ancient pines. No one knew if the question was meant for them, but in the clearing, a solitary sculpture of a hand reaching upwards seemed to respond. Carved from obsidian, 'The Crimson Touch' stood, fingers forever straining towards the sky, each line etched with the precision of a master artisan. Legend says that on certain nights, the moonlight catches the sculpture just right, casting a blood-red hue over the landscape, stirring the souls of those who wander too close."

**Example Input:**
The Guardian

Type: SculptureBronze
Material: Bronze
Quality: Good

On this work is an artwork of a dragon intertwined with a tree. The dragon's eyes are inlaid with emeralds, watching over a young girl. The overall composition is protective and mystical. This illustration tells the story of the young girl discovering her family legacy through the dragon guardian.

**Example Output:**
"In the bustling town square, 'The Guardian' stood proudly, a bronze dragon wrapped around a tree, its emerald eyes gleaming with a mischievous twinkle. Every morning, a young girl named Lily would walk by and tell the dragon her latest adventure, convinced it was her secret friend. One day, she found a note tucked under the dragon's claw that read, 'Nice story, but my tail itches.' Lily giggled and scratched the bronze tail, starting a town tradition where everyone now stops to 'scratch the dragon.' The mystical guardian had become the town's silliest superstition."

**Example Input:**
The Crumbling Legacy

Type: SculptureDecay
Material: Clay
Quality: Awful

On this work is an artwork of a figure attempting to hold a fragile structure. The scene depicts cracks and pieces falling off, with weeds growing through the gaps. The overall composition is bleak and deteriorating. This illustration tells the story of a failed attempt to preserve a once-great legacy.

**Example Output:**
"In the abandoned square of the colony, 'The Crumbling Legacy' stood as a stark reminder of ambition gone awry. The clay sculpture, depicting a figure desperately trying to support a fragile structure, was marred by deep cracks and missing pieces. Weeds sprouted through the gaps, symbolizing nature reclaiming its territory. Once intended to commemorate a great achievement, the sculpture now conveyed a bleak and deteriorating narrative of failure and neglect. As passersby gazed upon the dismal scene, a child whispered to her mother, 'Why did they let it fall apart?'"

### Input

$title

$description
""".strip()
    ),
)


trans_manager.register_template(
    "name_t",
    _(  # type: ignore
        r"""
You are an expert at naming items. Given a description, you always assign a name perfectly befitting the object. The name should reflect the item's characteristics and fit within the lore's tone and style. Given the passage below, provide the item with a name surrounded in quotes. Do not use more than 5 words.

**Example Input:**
"In the harsh desert world of Aridia, where the sun scorches the land and bandits roam, a leather duster of awful quality was found abandoned. Once a prized possession of a weary traveler, its tattered state tells tales of countless skirmishes and harsh journeys. The duster, though worn and beaten, still holds the faint scent of leather and the memories of survival against all odds."

**Example Output:**
"Tattered Traveler's Duster"

**Input:**
$pas
""".strip()
    ),
)

### END TRANSLATABLES ###
